services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gpp-cipher-dock
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - seed-data:/data
      - cron-output:/cron
      - ./keys/student_private.pem:/app/student_private.pem:ro
      - ./keys/student_public.pem:/app/student_public.pem:ro
      - ./keys/instructor_public.pem:/app/instructor_public.pem:ro
    environment:
      - TZ=UTC
    restart: unless-stopped

volumes:
  seed-data:
  cron-output: